import {chromium} from '/tmp/app-builder-d01b-browser/node_modules/playwright/index.mjs';
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=process.cwd(),out=path.resolve('../../docs/design/portal-system/v3');const index=JSON.parse(fs.readFileSync('storybook-static/index.json'));const stories=Object.values(index.entries).filter(e=>e.type==='story');assert.equal(stories.length,14);
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1100,height:800}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const results=[];
try{for(const story of stories){await page.goto('http://127.0.0.1:6006/iframe.html?id='+story.id+'&viewMode=story');await page.locator('#storybook-root > *').first().waitFor();await page.waitForTimeout(300);await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>[...document.fonts].some(f=>f.status==='error')),false,'Story font loading failed');assert.equal(await page.locator('.sb-errordisplay').isVisible(),false);await page.addScriptTag({path:root+'/node_modules/axe-core/axe.min.js'});const violations=await page.evaluate(async()=>{const r=await axe.run(document.querySelector('#storybook-root'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}));});assert.deepEqual(violations,[],story.id+': '+JSON.stringify(violations));
if(story.id==='patterns-decision-queue--many'){assert.equal(await page.locator('.decision-row').count(),3);assert.match(await page.locator('#storybook-root').innerText(),/Showing 3 of 20/);}
if(story.id==='patterns-decision-queue--zero'){assert.equal(await page.locator('.decision-row').count(),0);}
if(story.id==='patterns-decision-queue--unknown'){assert.match(await page.locator('#storybook-root').innerText(),/unavailable/);await page.getByRole('button',{name:'Try again'}).click();await page.getByText('3 open · 2 blocking · 1 optional',{exact:true}).waitFor();}
if(story.id==='primitives-status--chip-substitution'){assert.equal(await page.locator('mat-chip').innerText(),'Blocked');assert.equal(await page.locator('mat-chip').count(),1);}
results.push({id:story.id,render:'passed',axe:'passed'});console.log('PASS',story.id);}
// A deliberately false expectation must be detected by the same browser assertion mechanism.
await page.goto('http://127.0.0.1:6006/iframe.html?id=patterns-decision-queue--unknown&viewMode=story');await page.getByRole('button',{name:'Try again'}).click();await page.getByText('3 open · 2 blocking · 1 optional',{exact:true}).waitFor();let caught=false;try{assert.equal(await page.getByText('Decision count unavailable',{exact:true}).count(),1);}catch{caught=true;}assert.equal(caught,true);
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/workshop-validation.json',JSON.stringify({date:'2026-09-19',stories:results,negativeControl:'Deliberately incorrect expectation that retry leaves the count unavailable was rejected after the actual recovery interaction',componentSubstitution:'Status label replaced with Material chip through the same label input; browser rendering and axe passed',catalogDiscovery:stories.map(s=>({id:s.id,title:s.title,source:s.importPath})),errors,limitations:['Automatic source docgen disabled after two 120-second worker timeouts','Story index provides discovery; no preview MCP or automatic API manifest dependency','Axe subset is not a complete accessibility audit']},null,2));
}finally{await browser.close();}
