import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const url='http://127.0.0.1:4174/';
const click=a=>page.locator(`[data-action="${a}"]`).click();
const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('machine-d01b-borrowbox-v4')));
const go=async p=>{await page.goto(url+'#borrowbox/'+p);await page.waitForTimeout(60)};
const reset=async()=>{await click('reset');await go('overview')};
const ready=async()=>{await go('decisions/BB-D01?from=overview');await click('decision');await go('work/BB-001?from=affected')};
const produce=async()=>{await click('authorize');await click('map');await click('start');await click('finish')};
try{
await go('overview');await page.screenshot({path:'docs/evidence/d-01b-v4/overview.png',fullPage:true});
for(const count of [0,1,2]){await reset();await page.locator('#cardinality').selectOption(String(count));await go('decisions/BB-D01?from=overview');await click('decision');assert.match(page.url(),/decisions\/BB-D01/);assert.equal((await state()).auth.length,0);await page.getByRole('link',{name:`View ${count} affected tasks →`}).click();assert.match(page.url(),/work\?filter=affected/);assert.equal(await page.locator('main .row').count(),count);if(count===2){await page.getByRole('link',{name:'BB-001 · Reserve available tools'}).click();await page.getByRole('link',{name:'← Back to affected Work'}).click();assert.equal(await page.locator('main .row').count(),2)}}checks.push('T1/T2: zero, one and many affected records; answer stays on decision; no authorization; filtered return');
await ready();await produce();assert.equal((await state()).state,'Awaiting review');assert.match(page.url(),/work\/BB-001/);await page.getByRole('link',{name:'Review candidate →'}).click();assert.match(page.url(),/reviews\/A1/);await page.reload();assert.equal((await state()).artifacts.length,1);await page.screenshot({path:'docs/evidence/d-01b-v4/review.png',fullPage:true});
await click('missing');assert.ok(await page.locator('[data-action=accept]').isDisabled());await click('missing');await click('preview');assert.ok(await page.locator('[data-action=accept]').isDisabled());assert.equal(await page.locator('iframe').count(),0);await click('preview');
await page.getByLabel('Revision feedback').fill('Draft survives navigation');await go('work');await go('reviews/A1?from=task');await page.reload();assert.equal(await page.getByLabel('Revision feedback').inputValue(),'Draft survives navigation');checks.push('Unsaved review draft survives navigation and reload within the browser session');
const original=(await state()).artifacts[0];await page.getByLabel('Revision feedback').fill('Make occupied dates more prominent.');await click('revision');assert.equal((await state()).revisions.length,2);assert.equal((await state()).auth.length,1);await produce();await go('reviews/A1');assert.ok(await page.locator('[data-action=accept]').isDisabled());assert.deepEqual((await state()).artifacts[0],original);await go('reviews/A2');await click('accept');assert.equal((await state()).state,'Completed');assert.match(page.url(),/reviews\/A2/);assert.equal((await state()).reviews.at(-1).artifact,2);await click('stale');assert.ok(await page.locator('[data-action=accept]').isDisabled());assert.deepEqual((await state()).artifacts[0],original);checks.push('T7–T10: immutable candidate routes, reload, missing evidence/preview guards, A1 feedback → r2/A2, exact acceptance, stale protection');
for(const scenario of ['Worker unavailable','Connector unavailable','Connector conflict','Failure','Blocked input']){await reset();await ready();await page.locator('#scenario').selectOption(scenario);await click('authorize');assert.equal((await state()).state,'Authorized');await click('map');if(scenario==='Worker unavailable'){assert.equal((await state()).attempts.length,0);await click('cancel');await click('uncertain');assert.equal((await state()).state,'Cancellation uncertain');assert.equal(await page.locator('[data-action=authorize]').count(),0);await click('confirmCancel');await click('authorize');assert.equal((await state()).auth.length,2);continue}if(scenario.startsWith('Connector')){assert.equal((await state()).attempts.length,0);await click('reconcile')}await click('start');await click('finish');if(scenario==='Failure'){assert.equal((await state()).state,'Failed');await page.locator('#scenario').selectOption('Happy path');await produce();assert.equal((await state()).attempts[1].previousAttempt,1)}if(scenario==='Blocked input'){assert.equal((await state()).state,'Awaiting decision');await page.getByRole('link',{name:'Answer agent question →'}).click();await click('answer');assert.equal((await state()).state,'Continue ready');assert.equal((await state()).auth.length,1);assert.equal((await state()).revisions.length,2);await click('authorize');assert.equal((await state()).auth.length,2)}}checks.push('T3–T6: separate authorization/queue/claim; offline worker; connector unknown/conflict; uncertain cancellation; linked retry; answer requires continuation');
await reset();await ready();await produce();await page.setViewportSize({width:390,height:844});for(const path of ['overview','work?filter=affected','work/BB-001?from=affected','decisions/BB-D01','reviews/A1']){await go(path);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,path)}await page.screenshot({path:'docs/evidence/d-01b-v4/review-narrow.png',fullPage:true});
await go('work/BB-001?from=affected');await page.reload();await page.getByRole('link',{name:'← Back to affected Work'}).click();assert.match(page.url(),/filter=affected/);
await page.locator('main').focus();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.tagName),'A');const outline=await page.evaluate(()=>getComputedStyle(document.activeElement).outlineStyle);assert.equal(outline,'solid');
checks.push('T11: filtered deep-link reload; 390px overflow on five routes; keyboard Tab reaches a link with visible focus');
assert.deepEqual(errors,[]);checks.push('No JavaScript page errors');
await reset();await page.setViewportSize({width:1440,height:1000});
await writeFile('docs/evidence/d-01b-v4/validation.json',JSON.stringify({date:'2026-09-19',status:'passed',checks,errors,limits:['Agent browser checks do not prove owner usability','Static BorrowBox preview and synthetic check data','No live integration, recovery or implementation evidence']},null,2)+'\n');console.log(checks.join('\n'));
}finally{await browser.close()}
