import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { chromium } from './browser-support.mjs';

const origin = 'http://aludel.layers.localhost:4311';
const out = 'docs/evidence/lat-03';
mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 960 }, bypassCSP: true });
const api = context.request;
const calls = [];
async function request(method, path, data) {
  const response = await api.fetch(origin + path, { method, data, headers: { 'content-type': 'application/json' } });
  assert.ok(response.ok(), `${method} ${path} returned ${response.status()}: ${await response.text()}`);
  calls.push(`${method} ${path} ${response.status()}`);
  return response.json();
}
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
async function audit(name) {
  await page.addScriptTag({ path: 'apps/portal/node_modules/axe-core/axe.min.js' });
  const violations = await page.evaluate(async () => (await window.axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa'] } })).violations.map(v => v.id));
  assert.deepEqual(violations, [], `${name} axe`);
  await page.screenshot({ path: `${out}/${name}.png`, fullPage: true });
}
try {
  await request('PUT', '/api/onboarding/draft', { profile: 'planner' });
  await request('PUT', '/api/onboarding/draft', { name: `LAT03 ${randomBytes(3).toString('hex')}`, pitch: 'A local navigation acceptance fixture.' });
  const { project } = await request('POST', '/api/accounts', { name: 'LAT03 tester', email: `lat03-${randomBytes(6).toString('hex')}@example.test`, password: randomBytes(18).toString('hex') });
  const route = `/p/${project.slug}`;
  await page.goto(origin + route);
  await page.getByRole('heading', { name: project.name, exact: true }).waitFor();
  await audit('home-wide');
  const nav = page.getByRole('navigation', { name: 'Project navigation' });
  assert.deepEqual(await nav.getByRole('link').evaluateAll(links => links.map(link => link.textContent?.replace(link.querySelector('mat-icon')?.textContent || '', '').trim())), ['Home','Vision','Design','Pages','Data','Code','Deploy','Library','Work']);
  const instances = await request('GET', `/api/projects/${project.id}/layer-instances`);
  assert.equal(instances.layers.length, 6);
  await page.getByRole('checkbox', { name: 'In rail' }).nth(2).uncheck();
  await nav.getByRole('link', { name: 'Pages' }).waitFor({ state: 'detached' });
  assert.equal((await request('GET', `/api/projects/${project.id}/layer-instances`)).layers.find(v => v.key === 'pages').visible, false);
  await page.getByRole('checkbox', { name: 'On Home' }).nth(2).uncheck();
  await page.getByRole('region', { name: 'Layer cards' }).getByRole('link', { name: /Pages/ }).waitFor({ state: 'detached' });
  await page.reload();
  await page.getByRole('heading', { name: project.name, exact: true }).waitFor();
  assert.equal(await nav.getByRole('link', { name: 'Pages' }).count(), 0);
  await page.getByRole('checkbox', { name: 'In rail' }).nth(2).check();
  await nav.getByRole('link', { name: 'Pages' }).click();
  await page.getByRole('navigation', { name: 'Pages sections' }).waitFor();
  await audit('pages-wide');
  await page.getByRole('navigation', { name: 'Pages shared views' }).getByRole('link', { name: 'Operations' }).click();
  await page.getByRole('heading', { name: 'Operations' }).waitFor();
  await audit('operations-wide');
  await page.getByRole('navigation', { name: 'Pages shared views' }).getByRole('link', { name: 'Knowledge' }).click();
  await page.getByRole('heading', { name: 'Knowledge' }).waitFor();
  await page.goBack();
  await page.getByRole('heading', { name: 'Operations' }).waitFor();
  await page.goBack();
  await page.getByRole('navigation', { name: 'Pages sections' }).waitFor();
  await page.reload();
  await page.getByRole('navigation', { name: 'Pages sections' }).waitFor();
  const snapshot = (await request('GET', `/api/projects/${project.id}/knowledge`)).knowledge;
  assert.ok(snapshot.docs.length >= 2, 'fixture has two native documents');
  const docOne = `${origin}${route}/vision/docs/${snapshot.docs[0].id}`;
  await page.getByRole('searchbox', { name: 'Search every layer' }).fill(snapshot.docs[0].title);
  await page.locator('.lay-results a').filter({ hasText: snapshot.docs[0].title }).first().click();
  assert.ok(page.url().endsWith(`/vision/docs/${snapshot.docs[0].id}`), 'search opens exact document');
  const docTwo = `${origin}${route}/vision/docs/${snapshot.docs[1].id}`;
  await page.goto(docOne);
  await page.getByRole('navigation', { name: 'Vision sections' }).waitFor();
  await page.goto(docTwo);
  await page.getByRole('navigation', { name: 'Vision sections' }).waitFor();
  await page.goBack();
  assert.equal(page.url(), docOne, 'two-record Back navigation preserves the first exact URL');
  await page.goForward();
  assert.equal(page.url(), docTwo, 'two-record Forward navigation preserves the second exact URL');
  await page.reload();
  assert.equal(page.url(), docTwo, 'deep record URL survives reload');
  await nav.getByRole('link', { name: 'Vision' }).click();
  await page.getByRole('navigation', { name: 'Vision sections' }).waitFor();
  await nav.getByRole('link', { name: 'Library' }).click();
  await nav.getByRole('link', { name: 'Work' }).click();
  await nav.getByRole('link', { name: 'Home' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await audit('home-390');
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 2), '390px has no page-wide overflow');
  assert.deepEqual(errors, []);
  writeFileSync(`${out}/browser.json`, JSON.stringify({ projectId: project.id, checks: ['rail order','hide/show persists','Home cards','Pages','Operations','Knowledge','Back','Forward','two documents','search','reload','Vision','Library','Work','wide axe','390px axe'], calls, errors }, null, 2));
  console.log('LAT-03 browser acceptance passed');
} finally { await browser.close(); }
