import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { chromium } from './browser-support.mjs';

const origin = 'http://aludel.layers.localhost:4311';
const out = 'docs/evidence/lat-04';
mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 960 }, bypassCSP: true });
const api = context.request;
const calls = [];
async function request(method, path, data) {
  const response = await api.fetch(origin + path, { method, data, headers: { 'content-type': 'application/json' } });
  assert.ok(response.ok(), `${method} ${path} ${response.status()}: ${await response.text()}`);
  calls.push(`${method} ${path} ${response.status()}`);
  return response.json();
}
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
async function audit(name) {
  await page.addScriptTag({ path: 'apps/portal/node_modules/axe-core/axe.min.js' });
  const violations = await page.evaluate(async () => (await window.axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa'] } })).violations.map(v => v.id));
  assert.deepEqual(violations, [], `${name} axe`);
  await page.screenshot({ path: `${out}/${name}.png`, fullPage: true });
}
try {
  await page.goto(origin + '/start');
  await page.getByRole('radio').nth(1).check();
  await page.getByRole('button', { name: /Continue/i }).first().click();
  await page.getByRole('heading', { name: 'What are you making?' }).waitFor();
  await page.getByRole('textbox', { name: 'App name' }).fill(`LAT04 ${randomBytes(3).toString('hex')}`);
  await page.getByRole('textbox', { name: 'Elevator pitch' }).fill('A Pages only project for an isolated layer trial.');
  await page.getByRole('button', { name: /Continue/i }).first().click();
  await page.getByRole('heading', { name: /Which layers/i }).waitFor();
  assert.equal(await page.locator('.pub-layer-choice').count(), 6);
  await audit('catalog-wide');
  await page.getByRole('button', { name: 'Start with no layers' }).click();
  await page.getByRole('heading', { name: /Save .* to an? account/ }).waitFor();
  await request('POST', '/api/accounts', { name: 'LAT04 tester', email: `lat04-${randomBytes(6).toString('hex')}@example.test`, password: randomBytes(18).toString('hex') });
  await page.goto(origin + '/projects');
  const session = await request('GET', '/api/session');
  const project = session.projects.find(p => p.name.startsWith('LAT04 '));
  assert.ok(project);
  await page.goto(origin + `/p/${project.slug}`);
  await page.getByRole('heading', { name: project.name, exact: true }).waitFor();
  const nav = page.getByRole('navigation', { name: 'Project navigation' });
  assert.equal(await nav.getByRole('link', { name: 'Pages' }).count(), 0);
  await page.getByText('No layer apps yet.').waitFor();
  await audit('empty-home-wide');
  const emptyKnowledge = (await request('GET', `/api/projects/${project.id}/knowledge`)).knowledge;
  assert.equal(emptyKnowledge.pages.length, 0);
  assert.equal(emptyKnowledge.claims.length, 0);
  await page.getByRole('button', { name: 'Add Pages' }).click();
  await nav.getByRole('link', { name: 'Pages' }).waitFor();
  await nav.getByRole('link', { name: 'Pages' }).click();
  await page.getByRole('navigation', { name: 'Pages sections' }).waitFor();
  await audit('pages-wide');
  const isolated = (await request('GET', `/api/projects/${project.id}/knowledge`)).knowledge;
  assert.equal(isolated.pages.length, 0);
  assert.equal(isolated.claims.length, 0);
  await page.getByRole('navigation', { name: 'Pages shared views' }).getByRole('link', { name: 'Operations' }).click();
  await page.getByRole('heading', { name: 'Pages operations' }).waitFor();
  await page.getByRole('heading', { name: 'No Pages work yet' }).waitFor();
  await audit('operations-board-wide');
  await page.getByRole('navigation', { name: 'Pages operations sections' }).getByRole('link', { name: 'Connections' }).click();
  await page.getByRole('heading', { name: 'No neighboring layers' }).waitFor();
  await audit('connections-isolated-wide');
  await page.getByRole('navigation', { name: 'Pages operations sections' }).getByRole('link', { name: 'Routines' }).click();
  await page.getByRole('heading', { name: 'Pages routines' }).waitFor();
  await page.getByRole('button', { name: '+ Routine' }).click();
  await page.getByRole('heading', { name: 'New Pages routine' }).waitFor();
  await page.getByRole('textbox', { name: 'Name' }).fill('Check navigation labels');
  await page.getByRole('button', { name: 'Save definition' }).click();
  await page.getByRole('heading', { name: 'Check navigation labels' }).waitFor();
  await page.getByRole('navigation', { name: 'Pages shared views' }).getByRole('link', { name: 'Knowledge' }).click();
  await page.getByRole('heading', { name: 'Pages knowledge' }).waitFor();
  await page.getByRole('navigation', { name: 'Pages knowledge tree' }).getByRole('link', { name: /Map output/ }).first().click();
  const textArea = page.getByRole('textbox', { name: 'Document' });
  const before = await textArea.inputValue();
  await textArea.fill(before + '\nLAT-04 browser revision.');
  await page.getByRole('button', { name: 'Save new revision' }).click();
  await page.getByRole('button', { name: 'Read previous revision' }).click();
  await page.getByRole('heading', { name: /Earlier r1/ }).waitFor();
  await audit('knowledge-wide');
  await nav.getByRole('link', { name: 'Home' }).click();
  await page.getByRole('button', { name: 'Add Vision' }).click();
  await nav.getByRole('link', { name: 'Pages' }).click();
  await page.getByRole('navigation', { name: 'Pages shared views' }).getByRole('link', { name: 'Operations' }).click();
  await page.getByRole('navigation', { name: 'Pages operations sections' }).getByRole('link', { name: 'Connections' }).click();
  await page.getByRole('heading', { name: 'Vision → Pages' }).waitFor();
  await page.getByRole('button', { name: 'Draft connection' }).click();
  await page.getByRole('textbox', { name: 'Mapping instructions' }).fill('Use reviewed Vision stories as references for proposed Pages flows.');
  await page.getByRole('button', { name: 'Review and activate' }).click();
  await page.getByRole('heading', { name: /Vision → Pages/ }).getByText(/active · r/).waitFor();
  await nav.getByRole('link', { name: 'Home' }).click();
  await page.locator('.lay-layer-control').filter({ hasText: 'Vision' }).getByRole('button', { name: 'Remove' }).click();
  await nav.getByRole('link', { name: 'Vision' }).waitFor({ state: 'detached' });
  await nav.getByRole('link', { name: 'Pages' }).click();
  await page.getByRole('navigation', { name: 'Pages shared views' }).getByRole('link', { name: 'Operations' }).click();
  await page.getByRole('navigation', { name: 'Pages operations sections' }).getByRole('link', { name: 'Connections' }).click();
  const connection = (await request('GET', `/api/projects/${project.id}/layers/pages/connections`)).connections[0];
  assert.equal(connection.sourceAvailable, false);
  await page.setViewportSize({ width: 390, height: 844 });
  await audit('connections-390');
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 2), '390px has no page-wide overflow');
  const pagesContext = await browser.newContext({ viewport: { width: 1440, height: 960 } });
  const pagesOnboarding = await pagesContext.newPage();
  const pagesName = `Pages alone ${randomBytes(3).toString('hex')}`;
  await pagesOnboarding.goto(origin + '/start');
  await pagesOnboarding.getByRole('radio').nth(1).check();
  await pagesOnboarding.getByRole('button', { name: /Continue/i }).first().click();
  await pagesOnboarding.getByRole('textbox', { name: 'App name' }).fill(pagesName);
  await pagesOnboarding.getByRole('textbox', { name: 'Elevator pitch' }).fill('An isolated Pages layer with no other layer output.');
  await pagesOnboarding.getByRole('button', { name: /Continue/i }).first().click();
  await pagesOnboarding.getByRole('checkbox', { name: /Pages/i }).check();
  await pagesOnboarding.getByRole('button', { name: 'Continue with 1 layers' }).click();
  await pagesOnboarding.getByLabel('Your name').fill('Pages tester');
  await pagesOnboarding.getByLabel('Email').fill(`pages-${randomBytes(6).toString('hex')}@example.test`);
  const pagesPassword = randomBytes(18).toString('hex');
  await pagesOnboarding.getByLabel('Password', { exact: true }).fill(pagesPassword);
  await pagesOnboarding.getByLabel('Confirm password').fill(pagesPassword);
  await pagesOnboarding.getByRole('button', { name: 'Create account and continue' }).click();
  await pagesOnboarding.getByRole('heading', { name: /Give .* a home on GitHub/ }).waitFor();
  await pagesOnboarding.getByRole('button', { name: 'Continue with the local repository' }).click();
  await pagesOnboarding.getByRole('button', { name: 'Skip for now' }).click();
  await pagesOnboarding.getByRole('heading', { name: 'Shape the navigation' }).waitFor();
  assert.equal(await pagesOnboarding.locator('.pub-page-summary li').count(), 0);
  await pagesOnboarding.getByRole('button', { name: 'Continue' }).last().click();
  await pagesOnboarding.getByRole('heading', { name: pagesName, exact: true }).waitFor();
  const pagesSession = await pagesContext.request.get(origin + '/api/session').then(v => v.json());
  const pagesProject = pagesSession.projects.find(p => p.name === pagesName);
  assert.ok(pagesProject);
  const pagesInstances = await pagesContext.request.get(origin + `/api/projects/${pagesProject.id}/layer-instances`).then(v => v.json());
  assert.deepEqual(pagesInstances.layers.filter(v => v.enabled).map(v => v.key), ['pages']);
  await pagesContext.close();
  assert.deepEqual(errors, []);
  writeFileSync(`${out}/browser.json`, JSON.stringify({ projectId: project.id, checks: ['catalog','zero-layer home','Pages alone','native Pages','empty Operations','no neighbors','routine edit','knowledge revision','Vision connection review','source removal','Pages-only onboarding with blank navigation','wide and 390 axe'], calls, errors }, null, 2));
  console.log('LAT-04 browser acceptance passed');
} finally { await browser.close(); }
