import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { join } from 'node:path';
import { chromium } from './browser-support.mjs';

const origin = 'http://aludel.lat06.localhost:4312';
const out = 'docs/evidence/lat-06';
mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 960 }, bypassCSP: true });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const request = async (method, path, data) => {
  const response = await context.request.fetch(origin + path, { method, data, headers: { 'content-type': 'application/json' } });
  assert.ok(response.ok(), `${method} ${path}: ${response.status()} ${await response.text()}`);
  return response.json();
};
async function audit(name) {
  await page.addScriptTag({ path: 'apps/portal/node_modules/axe-core/axe.min.js' });
  const violations = await page.evaluate(async () => (await window.axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a','wcag2aa','wcag21aa'] } })).violations.map(value => value.id));
  assert.deepEqual(violations, [], `${name} axe`);
  await page.screenshot({ path: `${out}/${name}.png`, fullPage: true });
}
try {
  await page.goto(origin + '/start');
  await page.getByRole('radio').nth(1).check();
  await page.getByRole('button', { name: /Continue/i }).first().click();
  const name = `LAT06 ${randomBytes(3).toString('hex')}`;
  await page.getByRole('textbox', { name: 'App name' }).fill(name);
  await page.getByRole('textbox', { name: 'Elevator pitch' }).fill('Review a Code screen observation against Pages intent.');
  await page.getByRole('button', { name: /Continue/i }).first().click();
  await page.getByRole('button', { name: 'Start with no layers' }).click();
  await request('POST', '/api/accounts', { name: 'LAT06 tester', email: `lat06-${randomBytes(6).toString('hex')}@example.test`, password: randomBytes(18).toString('hex') });
  const session = await request('GET', '/api/session');
  const project = session.projects.find(value => value.name === name);
  assert.ok(project);
  const base = `/api/projects/${project.id}`;
  await request('PUT', `${base}/layer-instances/pages`, { enabled: true });
  await request('PUT', `${base}/layer-instances/platform`, { enabled: true });
  const db = new DatabaseSync('/tmp/aludel-lat06-browser/machine.sqlite');
  const workspace = db.prepare('SELECT workspace_path FROM project_setup WHERE project_id = ?').get(project.id).workspace_path;
  db.close();
  const path = 'src/routes/browse.ts';
  const marker = "export const browseRoute = '/browse';";
  mkdirSync(join(workspace, 'src/routes'), { recursive: true });
  writeFileSync(join(workspace, path), `${marker}\n`);
  execFileSync('git', ['add', '--', path], { cwd: workspace });
  execFileSync('git', ['-c', 'user.name=LAT06 fixture', '-c', 'user.email=lat06@example.invalid', 'commit', '-qm', 'Add disposable browse route'], { cwd: workspace });
  await page.goto(origin + `/p/${project.slug}/code/overview`);
  await page.getByRole('heading', { name: 'Code observations', exact: true }).waitFor();
  await page.getByText('Record a screen or route').click();
  await page.getByRole('textbox', { name: 'Tracked source path' }).fill(path);
  await page.getByRole('textbox', { name: 'Screen or route label' }).fill('Browse route');
  await page.getByRole('textbox', { name: 'Exact marker in the committed file' }).fill(marker);
  await page.getByRole('button', { name: 'Record pinned observation' }).click();
  await page.getByText('Browse route', { exact: true }).waitFor();
  await page.goto(origin + `/p/${project.slug}/pages/operations/connections`);
  await page.getByRole('heading', { name: 'Code observations → Pages candidates' }).waitFor();
  await page.getByRole('heading', { name: 'Browse route' }).waitFor();
  await page.getByRole('button', { name: 'Propose Pages relation' }).click();
  await page.getByRole('textbox', { name: 'Why this Code observation may inform Pages' }).fill('This source might describe the visitor entry route.');
  await page.getByRole('button', { name: 'Save proposed relation' }).click();
  await page.getByRole('textbox', { name: 'Review reason' }).fill('This source does not establish the intended visitor flow.');
  await page.getByRole('button', { name: 'Wrong relation' }).click();
  await page.getByText('wrong · r2').waitFor();
  await page.getByRole('button', { name: 'Propose Pages relation' }).click();
  await page.getByRole('textbox', { name: 'Why this Code observation may inform Pages' }).fill('The pinned source is useful for a separate Pages journey review.');
  await page.getByRole('button', { name: 'Save proposed relation' }).click();
  await page.getByRole('textbox', { name: 'Review reason' }).fill('Review the page journey without assuming Code proves intent.');
  await page.getByRole('button', { name: 'Useful candidate' }).click();
  await page.getByRole('button', { name: 'Suggest Pages task in Work' }).click();
  await page.getByRole('link', { name: 'Open Work item' }).waitFor();
  const relations = (await request('GET', `${base}/layers/pages/code-relations`)).relations;
  assert.deepEqual(relations.map(value => value.status).sort(), ['useful', 'wrong']);
  assert.ok(relations.find(value => value.status === 'useful').work_item_id);
  assert.equal(relations.find(value => value.status === 'wrong').work_item_id, null);
  await audit('code-relations-wide');
  await page.setViewportSize({ width: 390, height: 844 });
  await audit('code-relations-390');
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 2));
  assert.deepEqual(errors, []);
  writeFileSync(`${out}/browser.json`, JSON.stringify({ projectId: project.id, sourcePath: path, statuses: relations.map(value => value.status), errors,
    checks: ['source pin','wrong relation retained','useful relation staged once','Work link','wide axe','390 axe','no overflow'] }, null, 2));
  console.log('LAT-06 browser relation review passed');
} finally { await browser.close(); }
