import { chromium, ownerSignIn } from './browser-support.mjs';
import { randomBytes } from 'node:crypto';
import { openDatabase } from '../server/storage.mjs';
import { createProposal, reviseProposal } from '../server/product-records.mjs';
import { initWorkflow, workOperation } from '../server/workflow.mjs';
import assert from 'node:assert/strict';
const baseUrl = `http://127.0.0.1:${process.env.MACHINE_PORT || 4312}`;
for (let tries = 0; ; tries++) {
 try { const response = await fetch(`${baseUrl}/api/session`); if (response.ok) break; } catch {}
 if (tries >= 49) throw new Error('Test portal did not become ready');
 await new Promise(resolve => setTimeout(resolve, 100));
}
const db = openDatabase(`${process.env.MACHINE_DATA_DIR || '/tmp/machine-b03a-browser'}/machine.sqlite`); initWorkflow(db);
const browser = await chromium.launch({headless:true});
const page = await browser.newPage({viewport:{width:1440,height:1000},bypassCSP:true});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
 const key=randomBytes(24).toString('hex');
 await ownerSignIn(page, baseUrl, key);
 await page.getByRole('link',{name:'New request',exact:true}).click();
 await page.getByLabel('Your request').fill('Browser supervised cycle');
 await page.getByRole('button',{name:'Save request',exact:true}).click();
 await page.getByRole('heading',{name:'Request saved'}).waitFor();
 const req=db.prepare("SELECT id FROM owner_requests WHERE body = 'Browser supervised cycle'").get();
 const p=createProposal(db,{requestId:req.id,title:'Browser cycle',intent:'Validate handoff'},'operator');
 const triageAt=new Date().toISOString();
 db.prepare("INSERT INTO owner_requests(id,project_id,body,status,created_at,updated_at) VALUES ('REQ-browser-triage','the-machine','Browser triage signal','new',?,?)").run(triageAt,triageAt);
 let t=workOperation(db,'operator','prepare',{proposalId:p.id,proposalRevision:1,title:'Browser work',scope:'Local browser fixture',acceptance:'Owner answers persist'});
 await page.getByRole('link',{name:'Work',exact:true}).click();
 const second=workOperation(db,'operator','prepare',{proposalId:p.id,proposalRevision:1,title:'Second browser work',scope:'Second local fixture',acceptance:'Navigation preserves identity'});
 await page.reload();
 await page.getByRole('link',{name:/Second browser work/}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Authorize work',exact:true}).count(),0);
 await page.getByRole('link',{name:/Browser work/}).click();
 await page.getByRole('button',{name:'Authorize work',exact:true}).waitFor();
 await page.reload();
 await page.getByRole('link',{name:'Back to Agent operations'}).click();
 await page.locator('.operation-card').filter({has:page.getByRole('heading',{name:'Second browser work',exact:true})}).getByRole('link').click();
 assert.ok(page.url().endsWith(second.id));
 await page.getByRole('link',{name:'Back to Agent operations'}).click();
 await page.getByRole('link',{name:'Development plan',exact:true}).click();
 await page.getByRole('heading',{name:'Development plan',exact:true}).waitFor();
 await page.getByRole('link',{name:'Agent operations',exact:true}).click();
 await page.getByRole('heading',{name:'Agent operations',exact:true}).waitFor();
 await page.locator('.operation-card').filter({has:page.getByRole('heading',{name:'Browser work',exact:true})}).getByRole('link').click();
 await page.reload();
 await page.getByRole('button',{name:'Authorize work',exact:true}).click();
 await page.getByRole('heading',{name:'Queued for a worker'}).waitFor();
 const get=()=>JSON.parse(db.prepare('SELECT data FROM work_items WHERE id=?').get(t.id).data);
 t=get();t=workOperation(db,'operator','claim',{id:t.id,expectedVersion:t.version,worker:'test-worker'});
 t=workOperation(db,'operator','question',{id:t.id,expectedVersion:t.version,worker:t.worker,attempt:t.attempt,text:'Which local option?'});
 await page.reload();
 await page.getByLabel('Your answer',{exact:true}).fill('Use option A');
 await page.getByRole('button',{name:'Save answer'}).click();
 await page.getByRole('button',{name:'Resume authorized scope'}).waitFor();assert.equal(get().state,'paused');
 await page.getByRole('button',{name:'Resume authorized scope'}).click();await page.getByRole('heading',{name:'Queued for a worker'}).waitFor();
 t=get();t=workOperation(db,'operator','claim',{id:t.id,expectedVersion:t.version,worker:'test-worker'});
 workOperation(db,'operator','submit',{id:t.id,expectedVersion:t.version,worker:t.worker,attempt:t.attempt,text:'Browser evidence fixture: checks passed; no candidate acceptance.'});
 await page.reload();await page.getByRole('heading',{name:'Submitted evidence'}).waitFor();
 const recoveryProposal=createProposal(db,{title:'Recovery fixture',intent:'Prove changed-input recovery'},'operator');
 const recoveryTask=workOperation(db,'operator','prepare',{proposalId:recoveryProposal.id,proposalRevision:1,title:'Refresh changed inputs',scope:'Refresh for renewed review',acceptance:'No authorization is implied'});
 reviseProposal(db,recoveryProposal.id,{expectedRevision:1,title:'Recovery fixture revised'});
 await page.goto(`${baseUrl}/#/the-machine/work/operations`);
 await page.locator('.operation-card').filter({has:page.getByRole('heading',{name:'Refresh changed inputs',exact:true})}).getByRole('link').click();
 await page.getByRole('heading',{name:'Inputs changed'}).waitFor();
 await page.getByRole('button',{name:'Refresh inputs'}).click();
 await page.getByRole('heading',{name:'Ready for your authorization'}).waitFor();
 const recovered=JSON.parse(db.prepare('SELECT data FROM work_items WHERE id=?').get(recoveryTask.id).data);
 assert.equal(recovered.state,'ready');assert.equal(recovered.proposal.revision,2);
 const make=(title,state)=>{const proposal=createProposal(db,{title:`${title} proposal`,intent:title},'operator');let task=workOperation(db,'operator','prepare',{proposalId:proposal.id,proposalRevision:1,title,scope:`${title} scope`,acceptance:`${title} evidence`});if(state!=='ready')task=workOperation(db,'owner','authorize',{id:task.id,expectedVersion:task.version});if(['running','failed'].includes(state))task=workOperation(db,'operator','claim',{id:task.id,expectedVersion:task.version,worker:`${title.toLowerCase()}-agent`});if(state==='failed')task=workOperation(db,'operator','fail',{id:task.id,expectedVersion:task.version,worker:task.worker,attempt:task.attempt,text:'Fixture failure needs owner review.'});return {proposal,task};};
 make('Problem work','failed');
 make('Queued work','authorized');
 const blocked=make('Blocked work','ready');reviseProposal(db,blocked.proposal.id,{expectedRevision:1,title:'Blocked work revised'});
 make('Running work','running');
 await page.getByRole('link',{name:/Intake/}).click();
 await page.getByRole('heading',{name:'Intake',exact:true}).waitFor();
 await page.getByRole('button',{name:/Browser triage signal/}).click();
 await page.getByRole('button',{name:'Defer signal'}).click();
 await page.getByRole('button',{name:/Deferred · 1/}).waitFor();
 await page.getByRole('button',{name:/Browser triage signal/}).waitFor();
 await page.addScriptTag({path:'node_modules/axe-core/axe.min.js'});
 const axe=()=>page.evaluate(async()=>(await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations.map(v=>v.id));
 for(const view of [{path:'work',name:'overview'},{path:'work/plan',name:'plan'},{path:'work/operations',name:'operations'},{path:'work/intake',name:'intake'}]){
  await page.goto(`${baseUrl}/#/the-machine/${view.path}`);
  await page.locator('main h1').waitFor();
  assert.deepEqual(await axe(),[]);
  await page.screenshot({path:`test-results/work-${view.name}-wide.png`,fullPage:true});
 }
 await page.setViewportSize({width:390,height:844});
 await page.goto(`${baseUrl}/#/the-machine/work/operations`);
 await page.getByRole('heading',{name:'Agent operations',exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(await axe(),[]);assert.deepEqual(errors,[]);
 await page.screenshot({path:'test-results/work-operations-narrow.png',fullPage:true});
 console.log('PASS: four Work routes; request → prepare → authorize → claim → question → answer → resume → submit; Intake triage; wide/narrow axe and layout.');
} finally { db.close();await browser.close(); }
