import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openDatabase } from '../server/storage.mjs';
import { createProposal, reviseProposal } from '../server/product-records.mjs';
import { initWorkflow, workOperation as op, workList } from '../server/workflow.mjs';
test('supervised authorization, questions, cancellation and restart', () => {
 const path = join(mkdtempSync(join(tmpdir(),'machine-work-')), 'test.sqlite');
 let db = openDatabase(path); initWorkflow(db);
 const p = createProposal(db,{title:'Test',intent:'Test'});
 let t = op(db,'operator','prepare',{proposalId:p.id,proposalRevision:1,title:'Bounded test',scope:'Local test',acceptance:'Checks pass'});
 const input = extra => ({id:t.id,expectedVersion:t.version,worker:'codex-local',attempt:t.attempt,...extra});
 assert.throws(()=>op(db,'operator','authorize',input()),/cannot/);
 assert.throws(()=>op(db,'owner','claim',input()),/cannot/);
 assert.throws(()=>op(db,'operator','claim',input()),/Only authorized/);
 t=op(db,'owner','authorize',input());
 assert.throws(()=>op(db,'owner','authorize',input({expectedVersion:1})),/changed/);
 t=op(db,'operator','claim',input());
 assert.throws(()=>op(db,'operator','progress',input({attempt:'other',text:'No'})),/current worker/);
 t=op(db,'operator','question',input({text:'Which option?'}));
 t=op(db,'owner','answer',input({text:'Option A'})); assert.equal(t.state,'paused');
 assert.throws(()=>op(db,'operator','claim',input()),/Only authorized/);
 t=op(db,'owner','resume',input()); t=op(db,'operator','claim',input());
 t=op(db,'owner','cancel',input()); assert.equal(t.state,'cancelling');
 assert.throws(()=>op(db,'operator','submit',input({text:'Too late'})),/not running/);
 t=op(db,'operator','cancelled',input());
 db.close(); db=openDatabase(path);initWorkflow(db);
 assert.equal(workList(db)[0].state,'cancelled');assert.equal(workList(db)[0].events.length,9);
 const other=op(db,'operator','prepare',{proposalId:p.id,proposalRevision:1,title:'Second',scope:'Local',acceptance:'Pass'});
 reviseProposal(db,p.id,{expectedRevision:1,title:'Changed'});
 assert.throws(()=>op(db,'owner','authorize',{id:other.id,expectedVersion:other.version}),/Proposal changed/);
 assert.equal(workList(db).find(item=>item.id===other.id).input_status,'changed');
 const refreshed=op(db,'owner','refresh',{id:other.id,expectedVersion:other.version});
 assert.equal(refreshed.state,'ready');assert.equal(refreshed.proposal.revision,2);assert.equal(refreshed.input_status,'current');
 const authorized=op(db,'owner','authorize',{id:refreshed.id,expectedVersion:refreshed.version});
 assert.equal(authorized.state,'authorized');
 db.close();
});
