import {chromium} from '/tmp/app-builder-d01b-browser/node_modules/playwright/index.mjs';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=process.cwd();const evidence=path.resolve(root,'../../docs/design/portal-system/v3');const images=path.resolve(root,'../../tmp/the-machine-overview-concepts');fs.mkdirSync(images,{recursive:true});
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1487,height:1058},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));const checks=[];
const base='http://127.0.0.1:4173/';
async function fresh(query='',route='/borrowbox/overview') {await page.goto(base);await page.evaluate(()=>sessionStorage.clear());await page.reload();await page.goto(base+query+'#'+route);await page.locator('main h1').waitFor();await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>[...document.fonts].some(f=>f.status==='error')),false,'Font loading failed');}
async function check(name,fn){await fn();checks.push({name,status:'passed'});console.log('PASS',name);}
async function a11y(name){await page.addScriptTag({path:path.join(root,'node_modules/axe-core/axe.min.js')});const result=await page.evaluate(async()=>{const r=await axe.run(document.querySelector('main'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}));});assert.deepEqual(result,[],name+': '+JSON.stringify(result));}
try {
await check('Overview desktop: selected hierarchy, three decision rows, four tasks, honest preview',async()=>{await fresh();assert.equal(await page.locator('.decision-row').count(),3);assert.equal(await page.locator('.work-row').count(),4);assert.match(await page.locator('main').innerText(),/No preview yet/);await a11y('Overview');await page.screenshot({path:images+'/overview-built-wide.png'});});
await check('Zero, one, twenty and unavailable decision counts',async()=>{for(const [scenario,count] of [['zero',0],['one',1],['many',3],['unknown',3]]){await fresh('?scenario='+scenario);assert.equal(await page.locator('.decision-row').count(),count);if(scenario==='zero')assert.equal(await page.getByRole('link',{name:'Review decisions',exact:true}).count(),0);if(scenario==='many'){assert.match(await page.locator('main').innerText(),/Showing 3 of 20/);await page.getByRole('link',{name:'View all 20 decisions'}).click();assert.equal(await page.locator('.decision-row').count(),20);}if(scenario==='unknown'){assert.match(await page.locator('main').innerText(),/Decision count unavailable/);assert.equal(await page.getByText('Unverified',{exact:true}).count(),3);await page.getByRole('link',{name:'Decisions',exact:true}).click();assert.equal(await page.getByRole('link',{name:'Open',exact:true}).count(),1);await page.getByRole('button',{name:'Try again'}).click();assert.match(await page.locator('main').innerText(),/3 open/);}}});
await check('Decision save is explicit, stays on record, preserves remaining dependency',async()=>{await fresh();await page.locator('.decision-row').first().click();assert.match(page.url(),/BB-D01/);await page.getByRole('radio',{name:'Confirm instantly',exact:true}).check();assert.equal(await page.getByText('Answer saved.',{exact:true}).count(),0);await page.getByRole('button',{name:'Save answer',exact:true}).click();await page.getByText('Answer saved. No work has started.',{exact:true}).waitFor();assert.match(page.url(),/BB-D01/);assert.match(await page.locator('main').innerText(),/checks are still waiting/);await a11y('Decision saved');await page.getByRole('link',{name:'Back to Overview'}).click();assert.equal(await page.locator('.decision-row').count(),2);assert.match(await page.locator('.work-row').nth(0).innerText(),/Ready/);assert.match(await page.locator('.work-row').nth(1).innerText(),/Waiting/);await page.reload();assert.equal(await page.locator('.decision-row').count(),2);});
await check('Failed and conflicting saves retain draft; conflict requires explicit re-review',async()=>{for(const failure of ['error','conflict']){await fresh('?save='+failure,'/borrowbox/decisions/BB-D01');await page.getByRole('radio',{name:'Require volunteer approval',exact:true}).check();await page.getByRole('button',{name:'Save answer',exact:true}).click();await page.locator('.feedback').waitFor();assert.equal(await page.getByRole('radio',{name:'Require volunteer approval',exact:true}).isChecked(),true);assert.equal(await page.locator('.saved-answer').count(),0);await page.reload();assert.equal(await page.getByRole('radio',{name:'Require volunteer approval',exact:true}).isChecked(),true);if(failure==='conflict'){await page.getByRole('button',{name:'Save answer',exact:true}).click();await page.getByRole('button',{name:'Review current revision'}).click();assert.match(await page.locator('.eyebrow').innerText(),/revision 2/i);assert.equal(await page.locator('.saved-answer').count(),0);await page.getByRole('button',{name:'Save answer',exact:true}).click();await page.getByText('Answer saved. No work has started.',{exact:true}).waitFor();}}});
await check('Collection filter, browser return, scroll and deep-link fallback',async()=>{await fresh('?scenario=many','/borrowbox/decisions?filter=all');await page.locator('.decision-row').nth(10).scrollIntoViewIfNeeded();const y=await page.evaluate(()=>scrollY);await page.locator('.decision-row').nth(10).click();await page.goBack();await page.waitForTimeout(100);assert.match(page.url(),/filter=all/);assert.ok(Math.abs((await page.evaluate(()=>scrollY))-y)<30);await fresh('','/borrowbox/decisions/BB-D01');assert.match(await page.getByRole('link',{name:'Back to Decisions'}).getAttribute('href'),/filter=open/);});
await check('Request draft survives navigation/reload; failed save and discard dialog focus',async()=>{await fresh('?save=error','/borrowbox/request');await page.getByRole('textbox',{name:'Your request'}).fill('Let members extend a reservation.');await page.getByRole('link',{name:'Back to Overview'}).click();await page.getByRole('link',{name:'New request'}).click();assert.equal(await page.getByRole('textbox',{name:'Your request'}).inputValue(),'Let members extend a reservation.');await page.reload();await page.getByRole('button',{name:'Save request'}).click();await page.getByRole('alert').waitFor();assert.match(await page.getByRole('textbox',{name:'Your request'}).inputValue(),/extend/);await page.getByRole('button',{name:'Discard draft',exact:true}).click();await page.getByRole('dialog').waitFor();await a11y('Request');await page.getByRole('button',{name:'Keep writing'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.waitForTimeout(100);assert.equal(await page.getByRole('button',{name:'Discard draft',exact:true}).evaluate(e=>e===document.activeElement),true);await page.getByRole('button',{name:'Discard draft',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Discard draft',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelector('textarea').value==='');assert.equal(await page.getByRole('textbox',{name:'Your request'}).inputValue(),'');});
await check('Request happy path creates local fixture without starting work',async()=>{await fresh('','/borrowbox/request');await page.getByRole('textbox',{name:'Your request'}).fill('Allow a weekend collection window.');await page.getByRole('button',{name:'Save request'}).click();await page.getByText('Request saved locally',{exact:true}).waitFor();assert.match(await page.locator('main').innerText(),/No work has started/);});
await check('Keyboard reaches and answers a decision',async()=>{await fresh('','/borrowbox/decisions/BB-D01');await page.getByRole('radio',{name:'Confirm instantly',exact:true}).focus();await page.keyboard.press('Space');await page.keyboard.press('Tab');await page.keyboard.press('Enter');await page.getByText('Answer saved. No work has started.',{exact:true}).waitFor();});
await check('Narrow Overview and detail, readable navigation, no horizontal overflow',async()=>{await page.setViewportSize({width:390,height:844});await fresh();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await a11y('Narrow overview');await page.screenshot({path:images+'/overview-built-narrow.png',fullPage:true});await page.locator('.decision-row').first().click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.getByRole('radio',{name:'Confirm instantly',exact:true}).check();await a11y('Narrow decision');await page.screenshot({path:images+'/decision-built-narrow.png',fullPage:true});});
await check('Semantic primary token propagates to app link and Material button',async()=>{await page.setViewportSize({width:1487,height:1058});await fresh();const colors=()=>page.evaluate(()=>[getComputedStyle(document.querySelector('.row-copy strong')).color,getComputedStyle(document.querySelector('.queue-header .mat-mdc-unelevated-button')).backgroundColor]);const before=await colors();await page.addStyleTag({content:':root{--mat-sys-primary:#6b3189}'});const after=await colors();assert.notDeepEqual(before,after);assert.equal(after[0],'rgb(107, 49, 137)');assert.equal(after[1],'rgb(107, 49, 137)');});
assert.deepEqual(errors,[]);fs.writeFileSync(evidence+'/browser-validation.json',JSON.stringify({date:'2026-09-19',browser:browser.version(),viewport:{width:1487,height:1058},checks,errors,limitations:['Synthetic browser-local persistence; no server races or integrations','Automated axe subset and keyboard checks, not full screen-reader audit','Owner usability and adjacent page acceptance remain open']},null,2));
} finally {await browser.close();}
